### PR TITLE
shared: Add alt.off function reference validation

### LINKED ISSUE #229: Calling alt.off with invalid function reference breaks other listeners
### Description of the problem

See reproduction code.

### Reproduction steps

```js
const handler = (key) => {
  alt.log("keydown", key)
  listenKeydown()
}

const listenKeydown = () => {
  const [listener] = alt.getEventListeners("keydown")
  alt.log("keydown listener:", listener)

  if (listener) {
    alt.log("alt.off keydown with invalid function ref")
    alt.off("keydown", () => {})
  } else {
    alt.log("alt.on keydown")
    alt.on("keydown", handler)
  }
}

listenKeydown()
```

### Expected behaviour

Maybe we should check if passed function reference is not valid and throw error?

### Additional context

_No response_

### Operating system

Windows 11

### Version

13.0-rc2

### Scope

shared

### Reproduction tested

- [x] I confirm that I have made sure that this issue is also present on the newest dev version

### PR DESCRIPTION
**Pull request by xxshady**
Closes #229

### CODE REVIEW

**Review by LeonMrBonnie — APPROVED** [review]
doesn't really fix the underlying issue but fuck it

**Comment by xxshady** [comment]
изображение

**Comment by xxshady** [comment]
CgACAgQAAxkBAAFPYvtjjOdmTtARe5_rI7BEEOm7AspxagAC4AIAAm3mDFMpExhEyLAo6ysE_1670178710 88

**Comment by xxshady** [comment]
@LeonMrBonnie what fait awaits this PR?

**Comment by LeonMrBonnie** [comment]
was too lazy to press merge

**Pull request merged**
